version: 2.1
orbs:
  node: circleci/node@5.0.2
  coverage-reporter: codacy/coverage-reporter@13.11.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - node/install-packages
      - run: npm run test:coverage
      - coverage-reporter/send_report:
          coverage-reports: "coverage/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN
      - run: npm run build

workflows:
  build:
    jobs:
      - build
